
export const ANIMATION_PLAYING = 'ANIMATION_PLAYING';
export const ANIMATION_STOP = 'ANIMATION_STOP';

export const HEATMAP_LAYER_TOGGLE = 'HEATMAP_LAYER_TOGGLE';

export const SET_DAY = 'SET_DAY';

export const SET_CURRENT_ID = 'SET_CURRENT_ID';